### ISSUE TITLE
remove staged_dependencies.yaml

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/nestcolor#18]

**Comment by nikolas-burkoff** [comment]
@shajoezhu can you add a bit of context here (fyi @dinakar29) - if we remove the yaml file we'll need to remove nestcolor from tern/tmc's staged.deps yaml file and then nestcolor will no longer be part of our set of co-developed packages. This then has some consequences:

1) When installing nestcolor say in automation for tern it will **always** install the latest release of nestcolor ( https://github.com/insightsengineering/tern/blob/26fbef35279d706554ebddc495ca9ce67ef918d1/DESCRIPTION#L63) - this then means co-developing this package with the rest of NEST will not be possible.
 
2) We won't be able to use pre-release with nestcolor and it's then likely that this package won't follow the same release process as the rest of NEST

Just confirming is this what we are wanting?

**Comment by shajoezhu** [comment]
Hey @nikolas-burkoff , you are right about this. I completely agree, when i created this issue last night, was meaning to catch-up and discuss with you and @gogonzo in more details. From package dependency point of view, "nestcolor" provides a nice way of unify colors and theme for plots in tern, tmc, tlg-c, so we still include this in examples, so i guess we should still keep this with staged.dependency file. on second thought, i think we should still keep this file. i m closing this issue now. Thanks a lot for your comment!
