### ISSUE TITLE
cran release 0.1.2

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/nestcolor#49]
- [x] #51 
- [x] create cran_releae_0.1.2_branch
- [x] update DESCRIPTION
- [x]  Submission to CRAN
- [x]  Address any CRAN feedback
- [x] Acceptance on CRAN
- [ ] merge cran_releae_0.1.2_branch
- [ ] tag v0.1.2

**Comment by Melkiades** [comment]
Was it not here the problem that CRAN does not accept style packages? I remember that I proposed to change it to an util package and add a couple of functions from terns (utils packages are usually accepted)

**Comment by shajoezhu** [comment]
I hope this would be ok, there are other very light-weighted packages on cran, e.g. https://github.com/sjmgarnier/viridisLite

**Comment by shajoezhu** [comment]
https://cran.r-project.org/web/packages/nestcolor/index.html
